### ISSUE TITLE
Please consider a different namespace for Componere\Abstract\Definition

### ISSUE THREAD

**Issue by pprkut** [krakjoe/componere#5]
`Abstract` is not a valid namespace identifier in PHP, so you actually can't instantiate/extend/instanceof the class.
Now, you could argue that this class shouldn't be used by a programmer and thus it doesn't really matter, which is fair. However, there might be side-effects in some tools (static code analysis tools perhaps?). I think it would be nice if that wasn't something to worry about.

As for my motivation, I'm working on `kdev-php`, a PHP language plugin for the KDevelop IDE. It's generating PHP code from the PHP documentation to provide advanced syntax support. This all hinges on being able to generate valid PHP code from the documentation though. In this case I would create class definitions for `Componere\Abstract\Definition` and `Componere\Definition` to offer method auto completion, etc, but that doesn't work since `Abstract` isn't allowed as a namespace identifier.

I would really appreciate if you would consider a different, valid namespace name instead :)

**Comment by krakjoe** [comment]
> Now, you could argue that this class shouldn't be used by a programmer and thus it doesn't really matter, 

This is mentioned in the documentation ...

It's important, for the stability of any installation with componere loaded, that this particular abstract should not be used by the programmer in userland in any way, and since we lack the machinery to enforce this restriction by any other means, I'm not going to change the namespace. 

You can omit to generate documentation for this, any any other class you find in the manual (or upon reflection) with an "invalid" name quite safely.

If we had the machinery to declare that class private, which is what it is, then it wouldn't be in the documentation at all, it's present right now for the sake of completeness, and to give notice that you shouldn't attempt to use it ...

**Comment by pprkut** [comment]
Ok, fair enough. Didn't really cross my mind that it's intentionally that way to prevent instantiation, but it's reasonable. I can of course ignore the class in the documention, however, I assume its methods should still be inherited by `Componere\Definition`? They are declared public in the documentation so I assume they are callable ;)
I can 'move' them over from the Abstract class so they'd be available as well, guess that would be a good compromise.
